### PR TITLE
Adding classes and interfaces for subscribing and executing guard callback

### PR DESCRIPTION
**Pull request by juanjoarce7456**
This change is [Reviewable](https://reviewable.io/reviews/juanjoarce7456/petri_event_dispatcher/16)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 14 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 52 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv4zS0XsW_hUfm6qH5:-KYv4zS0XsW_hUfm6qH6:be3wgfz) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L52)):*
> ImmutableMap

why is this needed? unmodifiable can't be changed from that reference and this is a constant copy

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 72 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv8t08eOQOWBeDdjCK:-KYv8t08eOQOWBeDdjCL:bcr0f61) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L72)):*
> Boolean result = (Boolean) task.getGuardCallback(guardCallback).invoke(task.getObject());

surround with try{ ... } catch (NullPointerException ex) { Log or something }

HashMap.get(Object key) returns null when key doesn't exist

Don't add it to surround catch to try setting all guards

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java, line 43 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv7xa9NWLtoGZ8Xkz0:-KYv7xaA8tloo--x1UEc:b-wy59p6) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java#L43)):*
> guardName == ""

use guardName.isEmpty() instead

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java, line 70 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv9wl6Owzu59ydf2KK:-KYv9wl6Owzu59ydf2KL:b-lwki3o) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java#L70)):*
> boolean result = true;

not necessary

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java, line 73 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvA3tqP6pV5i5JORW6:-KYvA3tqP6pV5i5JORW7:bw910zf) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java#L73)):*
> for (Method m : getObject().getClass().getMethods()) {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>             if (result = method.equals(m)) {
>                 return result;
>             }
>         }
</details>

replace with 

for (Method m : getObject().getClass().getMethods()) {
     if (method.equals(m)) {
          return true;
     }
}
return false

---

*[BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java, line 51 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvAvYCgcA-vroZtSMz:-KYvAvYCgcA-vroZtSN-:b-2fl6n0) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java#L51)):*
> The method name provided should be of a method that does not take parameters in its signature.

too elaborated, hard to understand.

The given method must not take any arguments.

---

*[BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java, line 61 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvDZE3FKWM4ZWACc8g:-KYvDZE4HIw6PC3vBgd9:bdpsc9z) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java#L61)):*
> guardName

this may not be the same as the actual guard name. Maybe replace with guardProviderName

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 136 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvErVMNlEGx9JsImiZ:-KYvErVMNlEGx9JsImi_:b-sq9n8j) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L136)):*
> "The method should be annotated with HappeningHandler or Task annotations"

Asserting strings is not a good practice. If needed, use more specific exceptions. Else just leave it at that.
The message might change or be translated and all tests will fail then

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 587 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvHLdKa9JQ7XY7QPcO:-KYvHLdKa9JQ7XY7QPcP:br80k1x) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L587)):*
> contains

equals

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 588 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvHOregMda6VAXTiH4:-KYvHOregMda6VAXTiH5:br80k1x) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L588)):*
> contains

equals

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 599 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvHrGOhOV0kYS-sz6i:-KYvHrGOhOV0kYS-sz6j:b-cvsgb6) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L599)):*
> ```Java
>                     assertEquals(providerMethod1, key.getGuardCallback("g1").getName());
>                     assertEquals(providerMethod2, key.getGuardCallback("g2").getName());
>                 }
> ```

add a break finishing the if block

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 638 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvIHtsFXzuDZ8-pepp:-KYvIHtsFXzuDZ8-pepq:br80k1x) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L638)):*
> contains

equals

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 639 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvIJThjV_QzUyuf4_8:-KYvIJThjV_QzUyuf4_9:br80k1x) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L639)):*
> contains

equals

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 644 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvIOo50MsPBgcANfRa:-KYvIOo50MsPBgcANfRb:b-ohoxjm) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L644)):*
> assertTrue(e.getMessage().contains("There is not a GuardProvider annotated method with value"));

don't assert strings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16)*

**Comment by airabinovich** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16)*

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 52 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv4zS0XsW_hUfm6qH5:-KYvhA5fYP3nlkSNjo4k:b-lvb234) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L52)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> ImmutableMap

why is this needed? unmodifiable can't be changed from that reference and this is a constant copy
</blockquote></details>

UnmodifiableMap does not allow the insertion or deletion of elements on the collection, but it does not limit the modification of the objects referenced by the collections. I can still change an element field. Anyways, this function is for testing only, It's not going to be used constantly. Also, do we care if the user modifies the subscriptions, or it is a user problem if he wants to? 

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 72 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv8t08eOQOWBeDdjCK:-KYvjb_e8sp7CP7E-NTL:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L72)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> Boolean result = (Boolean) task.getGuardCallback(guardCallback).invoke(task.getObject());

surround with try{ ... } catch (NullPointerException ex) { Log or something }

HashMap.get(Object key) returns null when key doesn't exist

Don't add it to surround catch to try setting all guards
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java, line 43 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv7xa9NWLtoGZ8Xkz0:-KYvjt73Cb0xFZr3Btvb:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java#L43)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> guardName == ""

use guardName.isEmpty() instead
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java, line 70 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv9wl6Owzu59ydf2KK:-KYvk6iLw-PcGwvKJxDl:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java#L70)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> boolean result = true;

not necessary
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java, line 73 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvA3tqP6pV5i5JORW6:-KYvk7SMYQXMrY4umrRj:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTask.java#L73)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> for (Method m : getObject().getClass().getMethods()) {
>             if (result = method.equals(m)) {
>                 return result;
>             }
>         }

replace with 

for (Method m : getObject().getClass().getMethods()) {
     if (method.equals(m)) {
          return true;
     }
}
return false
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java, line 51 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvAvYCgcA-vroZtSMz:-KYvkHYJXX4rd5iz9upb:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java#L51)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> The method name provided should be of a method that does not take parameters in its signature.

too elaborated, hard to understand.

The given method must not take any arguments.
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java, line 61 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvDZE3FKWM4ZWACc8g:-KYvkLItc8iR5d8iGf2a:bfqr5i) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/utils/MethodDictionary.java#L61)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> guardName

this may not be the same as the actual guard name. Maybe replace with guardProviderName
</blockquote></details>

Actually, it's the actual guard name, it compares against the value of the @GuardProvider annotation and this annotation value is the name of the guard to resolve with the annotated method.

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 136 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvErVMNlEGx9JsImiZ:-KYvlNEdXetjYO3B9GRI:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L136)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> "The method should be annotated with HappeningHandler or Task annotations"

Asserting strings is not a good practice. If needed, use more specific exceptions. Else just leave it at that.
The message might change or be translated and all tests will fail then
</blockquote></details>

Done.

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 587 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvHLdKa9JQ7XY7QPcO:-KYvlNgsoGmjbaGPxutz:b-4dk5gd) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L587)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> contains

equals
</blockquote></details>

Actually it's not a string comparison. I am checking if the string "g1" exists on setGuardCallback, which is a list of strings. 

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 588 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvHOregMda6VAXTiH4:-KYvloBJzPvNLENhIEIU:b7aqhld) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L588)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> contains

equals
</blockquote></details>

checking if string exists on list of strings

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 599 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvHrGOhOV0kYS-sz6i:-KYvmAaS4Q9q0XdFCr4U:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L599)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

add a break finishing the if block
</blockquote></details>

Done.

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 638 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvIHtsFXzuDZ8-pepp:-KYvmCFo59t-wfjWr0cL:b7aqhld) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L638)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> contains

equals
</blockquote></details>

checking if string exists on list of strings

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 639 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvIJThjV_QzUyuf4_8:-KYvmJ4qiqEF53TjrIqv:b7aqhld) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L639)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> contains

equals
</blockquote></details>

checking if string exists on list of strings

---

*[BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java, line 644 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYvIOo50MsPBgcANfRa:-KYvlr6eXItzdPjW8kOF:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/test/org/unc/lac/baboon/test/cases/TasksAndHappeningHandlersSubscriptionTest.java#L644)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> assertTrue(e.getMessage().contains("There is not a GuardProvider annotated method with value"));

don't assert strings
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16)*

**Comment by airabinovich** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 52 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv4zS0XsW_hUfm6qH5:-KYxoMqShW2H9Pv6kEIi:bos56tt) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L52)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

UnmodifiableMap does not allow the insertion or deletion of elements on the collection, but it does not limit the modification of the objects referenced by the collections. I can still change an element field. Anyways, this function is for testing only, It's not going to be used constantly. Also, do we care if the user modifies the subscriptions, or it is a user problem if he wants to? 
</blockquote></details>

The user should not do that this way. If that feature is required in the future, some method unsubcribeFromTopic should do it

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 80 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYxpUs9w6R_GgVlc58w:-KYxpUsA_9Y9ppQeh82i:bd9s5p) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/689f2553f129514256483dad7ee0cbf36017fbfc/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L80)):*
> WARNING

this is a very important problem. Log level should be SEVERE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16)*

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 52 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv4zS0XsW_hUfm6qH5:-KYxr5QRAKrmgicoSRaZ:bqw8jl8) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L52)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

The user should not do that this way. If that feature is required in the future, some method unsubcribeFromTopic should do it
</blockquote></details>

Yeah, I'm not concerned about the way of subscribe or unsubscribe, I'm asking if allowing the subscription modification (even indirectly like in unmodifiable map) is a security issue or we let the unmodifiable map like that and we document the correct use.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 80 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYxpUs9w6R_GgVlc58w:-KYxsM1ZVX1AeA3hE8Ic:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/689f2553f129514256483dad7ee0cbf36017fbfc/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L80)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> WARNING

this is a very important problem. Log level should be SEVERE
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16)*

**Comment by airabinovich** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 52 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-KYv4zS0XsW_hUfm6qH5:-KYy8AjZMjFsJDEGuRBX:b-l4c2md) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/f4c4aa6c999cbf0baae9caa14e2589faa12d5fb0/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L52)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

Yeah, I'm not concerned about the way of subscribe or unsubscribe, I'm asking if allowing the subscription modification (even indirectly like in unmodifiable map) is a security issue or we let the unmodifiable map like that and we document the correct use.
</blockquote></details>

that may lead to unexpected behaviour either intentionally or unintentionally. I think it's better to protect the fileds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/16#-:-KYy9wcXqZ6JThHJO0iZ:bnfp4nl)*

**Pull request merged**
