### PR TITLE
Adding classes and tests for parsing a topics json file

### PR DESCRIPTION
**Pull request by juanjoarce7456**
This change is [Reviewable](https://reviewable.io/reviews/juanjoarce7456/petri_event_dispatcher/5)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java, line 5 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ4rbtHdQ4Gjh_2Dxi:-KWZ4rbunw9ATEUXNIB9:b-a6cutn) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java#L5)):_

> private static final long serialVersionUID = 1L;

use autogenerated serialVersionUID, it's a way to maintain version control of the serializable objects.
And if the class changes, compute it again.

> From https://dzone.com/articles/dont-ignore-serialversionuid:
> Declare a specific serialVersionUID, and update it whenever you make a change that breaks backward compatability.

---

_[BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java, line 7 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5HHJJMsNc2gC9Yr2:-KWZ5HHJJMsNc2gC9Yr3:b-5wojag) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java#L7)):_

> public BadTopicsJsonFormat(String errorMessage) {
>         super(errorMessage);

add default constructor

---

_[BaboonFramework/src/org/unc/lac/baboon/exceptions/NoTopicsJsonFileException.java, line 3 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5Nnqb6-MnPNVp1_7:-KWZ5Nnqb6-MnPNVp1_8:bnj7hl0) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/exceptions/NoTopicsJsonFileException.java#L3)):_

> ``` Java
> package org.unc.lac.baboon.exceptions;
> 
> public class NoTopicsJsonFileException extends Exception {
> ```

same as above

---

_[BaboonFramework/src/org/unc/lac/baboon/topic/Topic.java, line 15 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5c6EwmwNA3q1myl5:-KWZ5c6EwmwNA3q1myl6:btcx1oq) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/topic/Topic.java#L15)):_

> ``` Java
>  */
> public class Topic {
>     public String name; 
> ```

it's not a good practice to set all these fields as public.

It's best setting them as private and creating getters and setters with some restriction

---

_[BaboonFramework/src/org/unc/lac/baboon/utils/TopicsJsonParser.java, line 26 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5pfThFdqTr6AUQ9l:-KWZ5pfThFdqTr6AUQ9m:b-lo9v62) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/utils/TopicsJsonParser.java#L26)):_

> ``` Java
>  */
> public class TopicsJsonParser {
>     static ObjectMapper objectMapper = new ObjectMapper();
> ```

don't omit private modifier

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 20 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ7_dr-uDVJpVyPozd:-KWZ7_dr-uDVJpVyPoze:b-xik2sf) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L20)):_

> }

delete

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 38 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ7kAq278Gy5ak19pr:-KWZ7kArvcL2SiPJoGw7:bo2pb2f) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L38)):_

> "test/org/unc/lac/baboon/test/resources/topics.json"

define this as private final static String. You'll probably use it in newer tests

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 39 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ80tXSUZd3f5JnAXT:-KWZ80tXSUZd3f5JnAXU:bccjkfr) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L39)):_

> assertEquals(topics.size(),expectedNames.length);

arguments order is inverted, first is expected and second is actual. It's easier to debug id you respect it.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 46 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ8Pgl_4iaQ8r00tC_:-KWZ8Pgme5GnwJsU9asX:b-kdmwfv) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L46)):_

> ···

remove trailing spaces

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5)_

**Comment by juanjoarce7456** [comment]
Review status: 3 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

_[BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java, line 5 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ4rbtHdQ4Gjh_2Dxi:-KWcaewW-9RpSM1ybxT9:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java#L5)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > private static final long serialVersionUID = 1L;
> 
> use autogenerated serialVersionUID, it's a way to maintain version control of the serializable objects.
> And if the class changes, compute it again.
> 
> > From https://dzone.com/articles/dont-ignore-serialversionuid:
> > Declare a specific serialVersionUID, and update it whenever you make a change that breaks backward compatability.
> > </details>
> > Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java, line 7 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5HHJJMsNc2gC9Yr2:-KWcahFvhZRp0Hy1iHUf:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/exceptions/BadTopicsJsonFormat.java#L7)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > public BadTopicsJsonFormat(String errorMessage) {
> >         super(errorMessage);
> 
> add default constructor
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/exceptions/NoTopicsJsonFileException.java, line 3 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5Nnqb6-MnPNVp1_7:-KWcaiDQSSDNTQnblMx2:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/exceptions/NoTopicsJsonFileException.java#L3)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> same as above
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/topic/Topic.java, line 15 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5c6EwmwNA3q1myl5:-KWcem9qQOVHDEA_gmpM:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/topic/Topic.java#L15)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> it's not a good practice to set all these fields as public.
> 
> It's best setting them as private and creating getters and setters with some restriction
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/utils/TopicsJsonParser.java, line 26 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ5pfThFdqTr6AUQ9l:-KWceuXcBVlaT5OHd1ac:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/src/org/unc/lac/baboon/utils/TopicsJsonParser.java#L26)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> don't omit private modifier
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 20 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ7_dr-uDVJpVyPozd:-KWcfylBNuVk2sV1X42H:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L20)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > }
> 
> delete
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 38 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ7kAq278Gy5ak19pr:-KWcfgYAc2xIYY4ePYe9:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L38)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > "test/org/unc/lac/baboon/test/resources/topics.json"
> 
> define this as private final static String. You'll probably use it in newer tests
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 39 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ80tXSUZd3f5JnAXT:-KWcffFLxI4Iz_2mdrft:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L39)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > assertEquals(topics.size(),expectedNames.length);
> 
> arguments order is inverted, first is expected and second is actual. It's easier to debug id you respect it.
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java, line 46 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-KWZ8Pgl_4iaQ8r00tC_:-KWcffa98gmSyqCTJG7q:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/90a3bef530539650c2f6fa902affac0a7e2c8b91/BaboonFramework/test/org/unc/lac/baboon/test/cases/TopicsParserTest.java#L46)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > ···
> 
> remove trailing spaces
> 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5)_

**Comment by airabinovich** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r2.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5#-:-KWo02E8V3eQ_bW4g3rH:bnfp4nl)_

**Comment by airabinovich** [comment]
Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/5)_

**Pull request merged**
