### PR TITLE
Issue#4#8 set guards and happening handler advice

### PR DESCRIPTION
**Pull request by juanjoarce7456**
This change is [Reviewable](https://reviewable.io/reviews/juanjoarce7456/petri_event_dispatcher/18)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 21 of 22 files at r1.
Review status: 18 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningHandlerJoinPoint.aj, line 42 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-KcsnADtMdvT2TLkYq5t:-KcsnADuKldtX7IsgWHZ:bhkfru9) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningHandlerJoinPoint.aj#L42)):*
> This callback

These callbacks

---

*[BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningObserver.java, line 3 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-KcsmwfSh-t_cLRwKKvz:-KcsmwfSh-t_cLRwKKw-:b-awwrfn) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningObserver.java#L3)):*
> public interface HappeningObserver

Add some javadoc. It's impossible to figure out what this should do.
Methods too

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 51 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-KcsndNDNgSDX5jczcKM:-KcsndNDNgSDX5jczcKN:brqn5a9) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L51)):*
> public

can this be package-private instead of public?
if not, it's ok

---

*[BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java, line 44 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kcsr6bfGSaBNpmrp6Xa:-Kcsr6bfGSaBNpmrp6Xb:b-p8z0mr) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java#L44)):*
> ```Java
> 
>     @Override
>     public void updateAfter(Object target, String methodName) {
> ```

Both methods are the same but with different action after getting the subscription.

Maybe you could extract both into a single method who receives as parameter a method "action" and executes it.  
And from the calling side, updateAfter and updateBefore just call that method with different actions.

---

*[BaboonFramework/test/org/unc/lac/baboon/test/utils/tasks/MockController.java, line 25 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kcssfbl3ooIolhFo_qL:-KcssfbmBysn2TDGDVyp:bs7hxdp) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/test/org/unc/lac/baboon/test/utils/tasks/MockController.java#L25)):*
> ```Java
>     @HappeningHandler
>     public void mockHappeningHandler() {
>         
> ```

checkout this file to previous version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18)*

**Comment by juanjoarce7456** [comment]
Review status: 10 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningHandlerJoinPoint.aj, line 42 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-KcsnADtMdvT2TLkYq5t:-KcwZFSEGrtB7zJNtnFg:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningHandlerJoinPoint.aj#L42)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> This callback

These callbacks
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java, line 51 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-KcsndNDNgSDX5jczcKM:-KcwcXrtiP6_OM1CW699:b-vslxpr) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/main/BaboonConfig.java#L51)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> public

can this be package-private instead of public?
if not, it's ok
</blockquote></details>

It can't be package-private because of the tests. However, the user has no access to the BaboonConfig instance that is created in BaboonFramework 

---

*[BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java, line 44 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kcsr6bfGSaBNpmrp6Xa:-KcwbRY-dMAPhN6LxCMA:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java#L44)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

Both methods are the same but with different action after getting the subscription.

Maybe you could extract both into a single method who receives as parameter a method "action" and executes it.  
And from the calling side, updateAfter and updateBefore just call that method with different actions.
</blockquote></details>

Done.

---

*[BaboonFramework/test/org/unc/lac/baboon/test/utils/tasks/MockController.java, line 25 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kcssfbl3ooIolhFo_qL:-Kcwbk8fqYy29jljRgC0:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/test/org/unc/lac/baboon/test/utils/tasks/MockController.java#L25)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

checkout this file to previous version
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18)*

**Comment by juanjoarce7456** [comment]
Review status: 10 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningObserver.java, line 3 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-KcsmwfSh-t_cLRwKKvz:-KcwqGQ7-GXG_TYV0xQ8:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/happeninghandleraspect/HappeningObserver.java#L3)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> public interface HappeningObserver

Add some javadoc. It's impossible to figure out what this should do.
Methods too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18)*

**Comment by airabinovich** [comment]
Reviewed 4 of 22 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java, line 44 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kcsr6bfGSaBNpmrp6Xa:-Kd1LX6SZGUZ_XpXsKGS:b10ytth) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/becc863a14da392bfb46ce32820762acee0c6e5d/BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java#L44)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

beautiful!

---

*[BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java, line 64 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kd1KsmnJewU_0XQySE7:-Kd1KsmnJewU_0XQySE8:b-v0uydj) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/2a5b74d684be57d1f847f1ece2a7a25305df4ab9/BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java#L64)):*
> if (state == State.BEFORE_EXECUTION) {
>     before(happeningHandler);
> } else if (state == State.AFTER_EXECUTION) {
>     after(happeningHandler);

the classic switch case!

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTaskSubscription.java, line 67 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kd1Lz5A18xGaXU3VZkQ:-Kd1Lz5A18xGaXU3VZkR:b1g4vkl) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/2a5b74d684be57d1f847f1ece2a7a25305df4ab9/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTaskSubscription.java#L67)):*
>* This method returns a {@link Method} object to be called for obtaining
>* the value of the guard. It is intended to be used by the framework only,
>* the user should not call this method.

update this javadoc. Now you're returning the result of the method execution

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18)*

**Comment by juanjoarce7456** [comment]
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java, line 64 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kd1KsmnJewU_0XQySE7:-Kd1mvMjPUuL8P3AcEY6:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/2a5b74d684be57d1f847f1ece2a7a25305df4ab9/BaboonFramework/src/org/unc/lac/baboon/main/HappeningSynchronizer.java#L64)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> if (state == State.BEFORE_EXECUTION) {
>     before(happeningHandler);
> } else if (state == State.AFTER_EXECUTION) {
>     after(happeningHandler);

the classic switch case!
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/task/AbstractTaskSubscription.java, line 67 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-Kd1Lz5A18xGaXU3VZkQ:-Kd1mt04Si92YK_6_IA9:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/2a5b74d684be57d1f847f1ece2a7a25305df4ab9/BaboonFramework/src/org/unc/lac/baboon/task/AbstractTaskSubscription.java#L67)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

>* This method returns a {@link Method} object to be called for obtaining
>* the value of the guard. It is intended to be used by the framework only,
>* the user should not call this method.

update this javadoc. Now you're returning the result of the method execution
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18)*

**Comment by airabinovich** [comment]
:lgtm:

---

Reviewed 1 of 22 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/18#-:-Kd2DtqG8WhIGE260ytI:bnfp4nl)*

**Pull request merged**
