### PR TITLE
Issue#7, issue#10, issue#11

### PR DESCRIPTION
**Pull request by juanjoarce7456**
Adding Interfaces for initializing the Petri core
Adding a thread pool executor
Adding Dummy Threads for executing tasks

---
This change is [Reviewable](https://reviewable.io/reviews/juanjoarce7456/petri_event_dispatcher/13)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java, line 13 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXv--r6c0iOJyNaaiIG:-KXv--r7W_L-4Ujfbbkz:b-414v96) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java#L13)):*
> public DummiesExecutor()

pass the pool size as constructor parameter. This way, the pool size can be equal to the tasks amount

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java, line 14 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXv-PnqxCiIcZHUEsqO:-KXv-PnqxCiIcZHUEsqP:btn0lcd) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java#L14)):*
> TimeUnit.NANOSECONDS

We may have threads waiting for long periods of time, change this to minutes or hours

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 39 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXuw0oWP8BN1nHcKTxY:-KXuw0oXjC6B5ZftdsQt:b-uugag0) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L39)):*
> this.topic = topic;
> this.task = task;
> this.petriCore = petriCore;

check for nulls

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 56 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXv-ul5eI3DO-daYdqk:-KXv-ul6GSKw-oxUSva1:b-ob1shl) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L56)):*
> topic.getPermission()

what if this topic doesn't have permissions?
petriCore will throw an exception, and you will wrap it in a RuntimeException

is this expected? a topic can not have permissions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13)*

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java, line 13 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXv--r6c0iOJyNaaiIG:-KYUuJivRe71Q_fo7LuC:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java#L13)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> public DummiesExecutor()

pass the pool size as constructor parameter. This way, the pool size can be equal to the tasks amount
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java, line 14 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXv-PnqxCiIcZHUEsqO:-KYUuK5EqneHjGTT-L2q:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummiesExecutor.java#L14)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> TimeUnit.NANOSECONDS

We may have threads waiting for long periods of time, change this to minutes or hours
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 39 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXuw0oWP8BN1nHcKTxY:-KYUuKhSkn5Y9T_Bive_:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L39)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> this.topic = topic;
> this.task = task;
> this.petriCore = petriCore;

check for nulls
</blockquote></details>

Done.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 56 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KXv-ul5eI3DO-daYdqk:-KYUuL2Cjr5ggOxaRtXt:b-uda1hx) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/fd494953aa47053932b206cb8f6d92a1e90e4dfa/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L56)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> topic.getPermission()

what if this topic doesn't have permissions?
petriCore will throw an exception, and you will wrap it in a RuntimeException

is this expected? a topic can not have permissions?
</blockquote></details>

I'll create another patch for throwing an exception when trying to subscribe a Task to a topic with no permission. Happening Handlers can be executed with no permission but Tasks need permission.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13)*

**Comment by airabinovich** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonPetriCore.java, line 62 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KYV7aVFuS-d0h3lKS3D:-KYV7aVG-nJd6Vm-D1u1:br0ti5q) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/548b58f96f52afb8ae3f55fb6acd33dca78fcb33/BaboonFramework/src/org/unc/lac/baboon/main/BaboonPetriCore.java#L62)):*
> factory = new PetriNetFactory(pnmlFilePath);

factory is a static member. Either construct it once or make it an object member

---

*[BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java, line 70 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KYV7ElOqjZKuxh1n-cb:-KYV7ElOqjZKuxh1n-cc:b-nedms7) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/548b58f96f52afb8ae3f55fb6acd33dca78fcb33/BaboonFramework/src/org/unc/lac/baboon/main/DummyThread.java#L70)):*
> NotInitializedPetriNetException

this might have to be replced by PetriNetException in the future. Don't do it now though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13)*

**Comment by juanjoarce7456** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[BaboonFramework/src/org/unc/lac/baboon/main/BaboonPetriCore.java, line 62 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-KYV7aVFuS-d0h3lKS3D:-KYVL-VuATnzRf7R0XfH:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/548b58f96f52afb8ae3f55fb6acd33dca78fcb33/BaboonFramework/src/org/unc/lac/baboon/main/BaboonPetriCore.java#L62)):*
<details><summary><i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary><blockquote>

> factory = new PetriNetFactory(pnmlFilePath);

factory is a static member. Either construct it once or make it an object member
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13)*

**Comment by airabinovich** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/13#-:-KYZvImK646Bs-ZZp7ns:bnfp4nl)*

**Pull request merged**
