### PR TITLE
Adding framework's main class with automatic BaboonApplicationSetup

### PR DESCRIPTION
**Pull request by juanjoarce7456**
instantiation.
Adding BaboonApplicationSetup interface.
Adding Tests for main class.

---

This change is [Reviewable](https://reviewable.io/reviews/juanjoarce7456/petri_event_dispatcher/2)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[BaboonFramework/.gitignore, line 3 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1yJEHv4X900211TaM:-KV1yJEIy8gERCLzcsmW:b16v1d1) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/.gitignore#L3)):_

> ```
> 
> .metadata
> bin/
> ```

add build/

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV24VnAzvRp5YaKGvmf:-KV24VnFobqlJAvVpSlB:b-a9oi20) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java#L8)):_

> ``` Java
>  * The declare and subscribe method will be called automatically by the framework in that order.
>  */
> public interface BaboonApplicationSetup {
> ```

a class implementing this interface will be "the application"
in that case, we could rename this interface leaving the 'Setup' out

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java, line 10 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1ydDR-0wR4Eii1YfP:-KV1ydDSBx4-Nr-Fhmqu:b-1p73in) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java#L10)):_

> from main function.

don't put implementation details into javadoc, in its place specify when this will be called (initialization time, right after application launch, etc)

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java, line 15 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1yvDRyY3bjvTp8-9a:-KV1yvDRyY3bjvTp8-9b:brmrdxo) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java#L15)):_

> from main function.

same here

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KV1zNvf8hZYMdMWoU7r:b5xl1rz) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_

> public class BaboonFramework

add javadoc, some class explanation and specify all developers as authors

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 24 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV2-U5-H1iqJHWbAKVb:-KV2-U500oFUYuRq3WNU:b-yphw4j) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L24)):_

> ``` Java
>               appSetupObjects.add(app.newInstance());
>           } catch (IllegalAccessException | InstantiationException e) {
> 
> ```

is the case of abstract classes contemplated here?

what if an abstract class implements BaboonApplicationSetup?

maybe we could add a test for this case

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 20 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV207WU4RC3XaL7eY0X:-KV207WU4RC3XaL7eY0Y:b68qpnf) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L20)):_

> ``` Java
> 
>   /**
>    * <li> Given I run BaboonFramework's main </li>
> ```

this can be specified as tests background

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 22 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV22JUcawHKAtFFZZU7:-KV22JUdyq9Xd0uXQlXy:bdahgrk) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L22)):_

> @BeforeClass

Change this to Before, this way some test  may be affected by the others

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 31 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV21uFhtdh4oenpVVI3:-KV21uFhtdh4oenpVVI4:baurapk) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L31)):_

> And I get the log from log1

When I get the log from log1

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 32 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV21w3IkFgygSrs4CnM:-KV21w3IkFgygSrs4CnN:bu47f0u) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L32)):_

> When I check if the log contains "Declare"

Then the log contains "Declare"

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 33 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV221XZezFETmhLSmUb:-KV221XZezFETmhLSmUc:bwpm8fr) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L33)):_

> <li> Then the result is true </li>

remove this step

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java, line 10 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV23m9V1m9-kkdpa_pv:-KV23m9WR5yCpPs2ecuq:b-539ex3) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java#L10)):_

> ``` Java
> import java.util.logging.StreamHandler;
> 
> public class LogCatcher {
> ```

add some javadoc, even if it's testing code in a few weeks we'll forget why is this the way it is

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java, line 30 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV23WBzJs-CApn7UsYj:-KV23WBzJs-CApn7UsYk:b-q8a6w7) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java#L30)):_

> String result = logCapturingStream.toString();

return logCapturingStream.toString() directly, not neet of variable

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2)_

**Comment by juanjoarce7456** [comment]
Review status: 1 of 10 files reviewed at latest revision, 13 unresolved discussions.

---

_[BaboonFramework/.gitignore, line 3 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1yJEHv4X900211TaM:-KV6-1WE4-gHBvh-uYPM:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/.gitignore#L3)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> add build/
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KVBWLC6ggnNncVj3Uqc:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > public class BaboonFramework
> 
> add javadoc, some class explanation and specify all developers as authors
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 24 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV2-U5-H1iqJHWbAKVb:-KV6AE4RBf6w07s26Uh5:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L24)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> is the case of abstract classes contemplated here?
> 
> what if an abstract class implements BaboonApplicationSetup?
> 
> maybe we could add a test for this case
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 20 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV207WU4RC3XaL7eY0X:-KVBX9aX2Kd7r0FzY4u4:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L20)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> this can be specified as tests background
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 22 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV22JUcawHKAtFFZZU7:-KV6AW7QYlvjmZ46PXLC:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L22)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > @BeforeClass
> 
> Change this to Before, this way some test  may be affected by the others
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 31 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV21uFhtdh4oenpVVI3:-KV6AXCqJP9QPcNJ7uHc:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L31)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > And I get the log from log1
> 
> When I get the log from log1
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 32 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV21w3IkFgygSrs4CnM:-KV6AXl7WJdEpp5fr1mH:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L32)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > When I check if the log contains "Declare"
> 
> Then the log contains "Declare"
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 33 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV221XZezFETmhLSmUb:-KV6AYUDskEGBhMI615u:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L33)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > <li> Then the result is true </li>
> 
> remove this step
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java, line 10 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV23m9V1m9-kkdpa_pv:-KVBXBS1boYMdCp0AkMv:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java#L10)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> add some javadoc, even if it's testing code in a few weeks we'll forget why is this the way it is
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java, line 30 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV23WBzJs-CApn7UsYj:-KV6AdBJkswqwSGsAjzi:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java#L30)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > String result = logCapturingStream.toString();
> 
> return logCapturingStream.toString() directly, not neet of variable
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV24VnAzvRp5YaKGvmf:-KV6-ikEs8C-o7sZgI3t:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java#L8)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> a class implementing this interface will be "the application"
> in that case, we could rename this interface leaving the 'Setup' out
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java, line 10 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1ydDR-0wR4Eii1YfP:-KV6-mHDbwnLy9x0hLZl:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java#L10)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > from main function.
> 
> don't put implementation details into javadoc, in its place specify when this will be called (initialization time, right after application launch, etc)
> </details>
> Done.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java, line 15 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1yvDRyY3bjvTp8-9a:-KV6-m_m_w6UabBo7RO4:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonApplicationSetup.java#L15)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > from main function.
> 
> same here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2)_

**Comment by airabinovich** [comment]
Reviewed 10 of 12 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KVBpnTr_HV4yp8pMenT:bpeeqef) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Done.
> </details>
> Class description should be before author

http://www.oracle.com/technetwork/articles/java/index-137868.html

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 147 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVBs6E1IsEl5FHmmubq:-KVBs6E20RPx8o6lASOy:b-53hw4e) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/d3de20de419c5c2aab822d27f70f0ec43c7692c0/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L147)):_

> ``` Java
>         String capturedLog = logCatcher3.getTestCapturedLog();
>         Assert.assertTrue(capturedLog.contains(expectedLogForDeclareMethod + " Concrete"));
>         Assert.assertTrue(capturedLog.contains(expectedLogForSubscribeMethod + " Concrete"));
> ```

add some check for logger not including abstract class' info

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java, line 10 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV23m9V1m9-kkdpa_pv:-KVBrEcUFiFMPerqIYs9:blmdr29) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java#L10)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Done.
> </details>
> same as previous. review javadoc style

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/appsetup/AbstractAppSetup.java, line 13 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVBrZlIGP3Au4zyyeir:-KVBrZlIGP3Au4zyyeis:bnb6n3u) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/d3de20de419c5c2aab822d27f70f0ec43c7692c0/BaboonFramework/test/org/unc/lac/baboon/test/utils/appsetup/AbstractAppSetup.java#L13)):_

> ``` Java
>  */
> public abstract class AbstractAppSetup implements BaboonApplication {
> ```

you could implement declare and subscribe with specified strings here and check in the test these strings are not logged

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2)_

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KVGUDO71YmIDZdj0P7B:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> Class description should be before author
> 
> http://www.oracle.com/technetwork/articles/java/index-137868.html
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 147 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVBs6E1IsEl5FHmmubq:-KVGUFzWU7_6ringfmhu:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/d3de20de419c5c2aab822d27f70f0ec43c7692c0/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L147)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> add some check for logger not including abstract class' info
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java, line 10 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV23m9V1m9-kkdpa_pv:-KVGUGuHVL-x4KCY2ASe:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/test/org/unc/lac/baboon/test/utils/LogCatcher.java#L10)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> same as previous. review javadoc style
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/utils/appsetup/AbstractAppSetup.java, line 13 at r2](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVBrZlIGP3Au4zyyeir:-KVGULkK2uw9wBKDRfLO:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/d3de20de419c5c2aab822d27f70f0ec43c7692c0/BaboonFramework/test/org/unc/lac/baboon/test/utils/appsetup/AbstractAppSetup.java#L13)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> you could implement declare and subscribe with specified strings here and check in the test these strings are not logged
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2)_

**Comment by airabinovich** [comment]
Reviewed 7 of 10 files at r3.
Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KVGzAJ6C-4_kLyE0xa4:b38voph) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_

> <p>

if you're opening a section close it (</p>)

link structure is not required when quoting using @see 

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 181 at r3](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVH-Ey_CkmmRvApQrYO:-KVH-EyaO4zFPbgh0wNh:b-grz7w9) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/87347f822664c3b7fc6aa3a514bc0417e49d9043/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L181)):_

>  Assert.assertTrue(!condition)

Assert.assertFalse(condition) is easier to read

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 228 at r3](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVH-amSEnf1eOeyRJNZ:-KVH-amSEnf1eOeyRJN_:bsp2mrg) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/87347f822664c3b7fc6aa3a514bc0417e49d9043/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L228)):_

> Assert.assertTrue(!

same here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2)_

**Comment by juanjoarce7456** [comment]
Review status: 3 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KVHBIDv7adB8pLm7-JM:b-jv4n00) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > <p>
> 
> if you're opening a section close it (</p>)
> 
> link structure is not required when quoting using @see 
> </details>
> Done, nevertheless check this link: http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html, they don't close <p> sections
> Link structure removed.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 181 at r3](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVH-Ey_CkmmRvApQrYO:-KVHDo27g0YPiqRRVbJn:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/87347f822664c3b7fc6aa3a514bc0417e49d9043/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L181)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> >  Assert.assertTrue(!condition)
> 
> Assert.assertFalse(condition) is easier to read
> </details>
> Done.

---

_[BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java, line 228 at r3](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KVH-amSEnf1eOeyRJNZ:-KVHDnAUwwVLfWWUV-z0:b-896fix) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/87347f822664c3b7fc6aa3a514bc0417e49d9043/BaboonFramework/test/org/unc/lac/baboon/test/main/BaboonMainApplicationSetupTest.java#L228)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > Assert.assertTrue(!
> 
> same here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2)_

**Comment by airabinovich** [comment]
:lgtm:

ready! when merging, choose the option "merge and delete branch"

---

Reviewed 3 of 8 files at r4.
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java, line 8 at r1](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-KV1zNvf8hZYMdMWoU7q:-KVHZnivg9HXAr8AcJsw:b1az4m) ([raw file](https://github.com/juanjoarce7456/petri_event_dispatcher/blob/6d223ac4f0c2fed512f21502b002dbdfd472b7f2/BaboonFramework/src/org/unc/lac/baboon/main/BaboonFramework.java#L8)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Done, nevertheless check this link: http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html, they don't close <p> sections
> Link structure removed.
> </details>
> that's weird but ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/juanjoarce7456/petri_event_dispatcher/2#-:-KVH_UJ6n8nFKBQJD667:bknimwn)_

**Pull request merged**
